export enum ActivityType {
  LEAD_CREATED = "LEAD_CREATED",
  STATUS_CHANGED = "STATUS_CHANGED",
  NOTE_ADDED = "NOTE_ADDED",
  LEAD_ASSIGNED = "LEAD_ASSIGNED",
  QUOTATION_CREATED = "QUOTATION_CREATED",
  QUOTATION_ACCEPTED = "QUOTATION_ACCEPTED",
  QUOTATION_REJECTED = "QUOTATION_REJECTED",
}

export enum LeadStatus {
  NEW = "NEW",
  CONTACTED = "CONTACTED",
  QUALIFIED = "QUALIFIED",
  PROPOSAL = "PROPOSAL",
  NEGOTIATION = "NEGOTIATION",
  WON = "WON",
  LOST = "LOST",
}
